### ISSUE TITLE
Crew page

### ISSUE THREAD

**Issue by natesheehan** [LOOSE-LIPS/loose-lips-2.0#1]
Summary:

    Set up the crew page in the same format as the current blog page

ToDo: 

- [x] Allow crew members to be added using a predefined markdown template that includes fields for image, name, description, and tags. 
- [x] Enable the export of crew members into components for use on other pages of the website. 
- [x] Implement search and filter functionality for the crew page

Notes:
It would also be helpful to find a full list of the crew before - either by the database or the old site.....

**Comment by Lewisthiverval** [comment]
woohoo first issue done
