### ISSUE TITLE
Add soundclound and mixcloud icon links

### ISSUE THREAD

**Issue by natesheehan** [LOOSE-LIPS/loose-lips-2.0#7]
Description: The menu icons could do with soundcloud and mixcloud. While at it, we could change the all of the icons so they all follow a particular style.

ToDo:

- [ ] Add soundcloud and mixcloud icons
- [ ] Update all icons so they are of the same design

**Comment by natesheehan** [comment]
@Lewisthiverval this could be a quick fix and win for us

**Comment by natesheehan** [comment]
@Lewisthiverval this could be a quick fix and win for us

**Comment by Lewisthiverval** [comment]
Yep will get that done asap

**Comment by natesheehan** [comment]
@t-scale do you think you could link us up with the assets you wanted for links e.g. mixcloud, soundcloud etc
